# Parameters to launch an image saver with the Intel RealSense d435 camera
depth:                true                                        # If depth images have to be stored
frequency:            1.0                                         # Frequency of images storage


depth_path:           "/src/cameras/images/d435"                  # Folder path to save depth images
color_path:           "/src/cameras/images/d435"                  # Folder path to save color images

depth_image_topic:    "/camera/aligned_depth_to_color/image_raw"  # Depth camera topic
color_image_topic:    "/camera/color/image_raw"                   # Color camera topic

counter_limit_color:  10                                          # Number of color images to store
counter_limit_depth:  10                                          # Number of depth images to store